server:
  port: 8081
spring:
  application:
    name: "flx-crm-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:h2:mem:testcrm"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: "update"
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
